crazyEye/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from web.views import base
from web import api_urls
from web.views import asset
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'session_security/', include('session_security.urls')),
    url(r'^$', base.home, name='dashboard'),
    url(r'^login/$', base.acc_login),
    url(r'^logout/$', base.acc_logout),
    url(r'^hosts/$', base.hosts, name='host_list'),
    url(r'^auditlog/$', base.auditlog, name='auditlog'),
    url(r'^host_mgr/cmd/$', base.host_mgr, name='batch_cmd'),
    url(r'^host_mgr/file_transfer/$', base.file_transfer, name='file_transfer'),
    url(r'^batch_task_mgr/$', base.batch_task_mgr, name='batch_task_mgr'),
    url(r'^task_result/$', base.task_result, name='get_task_result'),
    url(r'^user_audit/(\d+)/$',base.user_audit, name='user_audit'),
    url(r'^multi_task/log/deatail/(\d+)/$', base.multi_task_log_detail, name='multi_task_log_detail'),

    url(r'^asset.html$', asset.AssetListView.as_view()),
    url(r'^assets.html$', asset.AssetJsonView.as_view()),
    url(r'^asset-(?P<asset_nid>\d+).html$', asset.AssetDetailView.as_view()),
    url(r'^add-asset.html$', asset.AddAssetView.as_view()),

    url(r'^api/', include(api_urls)),

    url(r'^password_reset/',base.password_reset, name='password_reset'),
    url(r'^personal/', base.personal, name='personal'),
    url(r'^kingadmin/',include('kingadmin.urls')),


]

kingadmin/urls.py
from django.conf.urls import url,include
from kingadmin import views

urlpatterns = [

    url(r'^login/$', views.acc_login, name="acc_login"),
    url(r'^logout/$', views.acc_logout, name="acc_logout"),
    url(r'^(\w+)/(\w+)/change/(\d+)/password/$', views.password_reset_form, name='password_reset'),
    url(r'^account/password_reset/$', views.personal_password_reset, name='personal_password_reset'),

    url(r'^$', views.app_index, name="table_index"),  # 显示所有注册的表
    url(r'^(\w+)/$', views.app_tables, name="app_tables"),  # 显示每个app里所有注册的表
    url(r'^(\w+)/(\w+)/$',views.display_table_list,name="table_list"), #显示每个表的数据
    url(r'^(\w+)/(\w+)/add/$', views.table_add, name="table_add"),
    url(r'^(\w+)/(\w+)/change/(\d+)/$', views.table_change, name="table_change"),
    #
    url(r'^(\w+)/(\w+)/delete/(\d+)/$', views.table_del, name="table_del"),


]

web/models.py
from django.db import models
import django
from web import auth

# Create your models here.

class Host(models.Model):
    """存储主机列表"""
    name = models.CharField(max_length=64,unique=True)
    ip_addr = models.GenericIPAddressField(unique=True)
    port = models.SmallIntegerField(default=22)
    idc = models.ForeignKey("IDC")
    system_type_choices = (
        ('0','Windows'),
        ('1', 'Linux/Unix')
    )
    system_type = models.CharField(choices=system_type_choices,max_length=32,default='1')
    enabled = models.BooleanField(default=True, help_text='主机若不想被用户访问可以去掉此选项')
    memo = models.CharField(max_length=128, blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    #remote_users = models.ManyToManyField("RemoteUser")

    def __str__(self):
        return self.name
    class Meta:
        verbose_name = '主机'
        verbose_name_plural = '主机'

class HostGroup(models.Model):
    """存储主机组"""
    name = models.CharField(max_length=64,unique=True)
    memo = models.CharField(max_length=128, blank=True, null=True)
    host_to_remote_users = models.ManyToManyField("HostToRemoteUser")

    def __str__(self):
        return self.name
    class Meta:
        verbose_name = '主机组'
        verbose_name_plural = '主机组'

class HostToRemoteUser(models.Model):
    """绑定主机和远程用户的对应关系"""
    host = models.ForeignKey("Host")
    remote_user = models.ForeignKey("RemoteUser")

    enabled = models.BooleanField(default=True)
    class Meta:
        unique_together = ("host", "remote_user")
        verbose_name = '主机与远程用户绑定'
        verbose_name_plural = '主机远程与用户绑定'

    def __str__(self):
        return "%s %s"%(self.host,self.remote_user)

class RemoteUser(models.Model):
    """存储远程要管理的主机的账号信息"""
    auth_type_choices = ((0,'ssh-password'),(1,'ssh-key'))
    auth_type = models.SmallIntegerField(choices=auth_type_choices,default=0,help_text='如果选择SSH/KEY，请确保你的私钥文件已在settings.py中指定')
    username = models.CharField(max_length=32)
    password = models.CharField(max_length=64,blank=True,null=True,help_text='如果auth_method选择的是SSH/KEY,那此处不需要填写..')
    memo = models.CharField(max_length=128,blank=True,null=True)
    def __str__(self):
        return '%s(%s)' %(self.username,self.password)
    class Meta:
        verbose_name = '远程用户'
        verbose_name_plural = '远程用户'
        unique_together = ('auth_type','password','username')


class UserProfile(auth.AbstractBaseUser,auth.PermissionsMixin):
    """堡垒机账号"""
    email = models.EmailField(
        verbose_name='email address',
        max_length=255,
        unique=True,
    )
    name = models.CharField(max_length=64, verbose_name="姓名")
    is_active = models.BooleanField(default=True)
    is_admin = models.BooleanField(default=False)
    is_staff = models.BooleanField(default=True)

    department = models.ForeignKey('Department', verbose_name='部门', blank=True, null=True)

    host_to_remote_users = models.ManyToManyField("HostToRemoteUser",blank=True)
    host_groups = models.ManyToManyField("HostGroup",blank=True)

    memo = models.TextField('备注', blank=True, null=True, default=None)
    date_joined = models.DateTimeField(blank=True, null=True, auto_now_add=True)
    valid_begin_time = models.DateTimeField(default=django.utils.timezone.now, help_text="yyyy-mm-dd HH:MM:SS")
    valid_end_time = models.DateTimeField(blank=True, null=True, help_text="yyyy-mm-dd HH:MM:SS")

    USERNAME_FIELD = 'email'    # 哪个字段当作用户名
    REQUIRED_FIELDS = ['name']  # 必须字段

    objects = auth.UserManager()    # 创建用户的方法

    def get_full_name(self):
        # The user is identified by their email address
        return self.email

    def get_short_name(self):
        # The user is identified by their email address
        return self.email

    def __str__(self):              # __unicode__ on Python 2
        return self.email

    class Meta:
        verbose_name = 'CrazyEye账户'
        verbose_name_plural = 'CrazyEye账户'

        permissions = (
            ('web_access_dashboard', '可以访问 审计主页'),
            ('web_batch_cmd_exec', '可以访问 批量命令执行页面'),
            ('web_batch_batch_file_transfer', '可以访问 批量文件分发页面'),
            ('web_config_center', '可以访问 堡垒机配置中心'),
            ('web_config_items', '可以访问 堡垒机各配置列表'),
            ('web_invoke_admin_action', '可以进行admin action执行动作'),
            ('web_table_change_page', '可以访问 堡垒机各配置项修改页'),
            ('web_table_change', '可以修改 堡垒机各配置项'),
        )
class IDC(models.Model):
    """机房信息"""
    name = models.CharField(max_length=64,unique=True)
    def __str__(self):
        return self.name
    class Meta:
        verbose_name = 'IDC'
        verbose_name_plural = 'IDC'

class SessionTrack(models.Model): #没用了的表

    date = models.DateTimeField(auto_now_add=True)
    closed = models.BooleanField(default=False)
    def __str__(self):
        return '%s' %self.id


class Session(models.Model):
    '''生成用户操作session id '''
    user = models.ForeignKey('UserProfile')
    bind_host = models.ForeignKey('HostToRemoteUser')
    tag = models.CharField(max_length=128,default='n/a')
    closed = models.BooleanField(default=False)
    cmd_count = models.IntegerField(default=0) #命令执行数量
    stay_time = models.IntegerField(default=0, help_text="每次刷新自动计算停留时间",verbose_name="停留时长(seconds)")
    date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return '<id:%s user:%s bind_host:%s>' % (self.id,self.user.email,self.bind_host.host)
    class Meta:
        verbose_name = '审计日志'
        verbose_name_plural = '审计日志'


class AuditLog(models.Model):
    """存储审计日志"""
    session = models.ForeignKey(SessionTrack,null=True,blank=True)
    user = models.ForeignKey("UserProfile",verbose_name="堡垒机账号",null=True,blank=True)
    host_to_remote_user = models.ForeignKey("HostToRemoteUser" ,null=True,blank=True)
    action_choices = (
        (0,'CMD'),
        (1,'Login'),
        (2,'Logout'),
        (3,'GetFile'),
        (4,'SendFile'),
        (5,'exception'),
    )
    log_type = models.SmallIntegerField(choices=action_choices,default=0)
    content = models.CharField(max_length=255,null=True,blank=True)
    date = models.DateTimeField(auto_now_add=True,null=True,blank=True)
    memo = models.CharField(max_length=128, blank=True, null=True)

    def __str__(self):
        return "%s %s" %(self.host_to_remote_user, self.content)
    class Meta:
        verbose_name = '审计日志old'
        verbose_name_plural = '审计日志old'

class Department(models.Model):
    name = models.CharField(max_length=64,unique=True)
    def __str__(self):
        return self.name
    class Meta:
        verbose_name = '部门'
        verbose_name_plural = '部门'

class Task(models.Model):
    """批量任务"""
    start_time = models.DateTimeField(auto_now_add=True)
    end_time = models.DateTimeField(null=True, blank=True)
    task_type_choices = (('cmd','批量命令'),('file-transfer','文件传输'))

    task_type = models.CharField(choices=task_type_choices,max_length=64)
    content = models.CharField(max_length=255, verbose_name="任务内容")
    user = models.ForeignKey("UserProfile")
    hosts = models.ManyToManyField('HostToRemoteUser')
    expire_time = models.IntegerField(default=30)
    task_pid = models.IntegerField(default=0)
    note = models.CharField(max_length=100, blank=True, null=True)

    def __str__(self):
        return "taskid:%s type:%s cmd: %s"%(self.id,self.task_type,self.content)
    class Meta:
        verbose_name = '批量任务'
        verbose_name_plural = '批量任务'

class TaskLogDetail(models.Model):
    """存储大任务子结果"""
    task = models.ForeignKey("Task")
    host_to_remote_user = models.ForeignKey("HostToRemoteUser")
    result = models.TextField(verbose_name="任务执行结果")

    status_choices = ((0,'initialized'),(1,'sucess'),(2,'failed'),(3,'timeout'))
    status = models.SmallIntegerField(choices=status_choices,default=0)
    note = models.CharField(max_length=100, blank=True)
    date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return "%s %s"%(self.task,self.host_to_remote_user)
    class Meta:
        verbose_name = '批量任务日志'
        verbose_name_plural = '批量任务日志'

class Token(models.Model):
    user = models.ForeignKey(UserProfile)
    host = models.ForeignKey(HostToRemoteUser)
    token = models.CharField(max_length=64)
    date = models.DateTimeField(default=django.utils.timezone.now)
    expire = models.IntegerField(default=300)

    def __str__(self):
        return '%s : %s' % (self.host.host.ip_addr, self.token)

templates/add_asset.html
{% extends 'index.html' %}

{% block top-css %}
    <link rel="stylesheet" href="/static/css/backend.css"/>
    <link rel="stylesheet" href="/static/css/commons.css"/>
{% endblock %}

{% block page-title %}
新增
{% endblock %}

{% block breadcrumb %}
    <ol class="breadcrumb" style="margin-bottom: 0;">
        <li><a href="/cmdb.html">首页</a></li>
        <li><a href="/asset.html">资产列表</a></li>
        <li class="active">添加资产</li>
    </ol>
{% endblock %}

{% block page-content %}

    <div style="padding: 5px 8px;">


    </div>



{% endblock %}

{% block js %}
    <script type="text/javascript" src="/static/js/jquery.cookie.js"></script>
    <script type="text/javascript" src="/static/plugins/bootstrap/js/bootstrap.js"></script>
    <script type="text/javascript" src="/static/js/nb-list.js"></script>

    <script>
        $(function () {
            $.initMenu('#menu_asset');
        });


    </script>
{% endblock %}

templates/asset_detail.html
{% extends 'index.html' %}

{% block top-css %}
    <link rel="stylesheet" href="/static/css/backend.css"/>
    <link rel="stylesheet" href="/static/css/commons.css"/>
{% endblock %}

{% block page-title %}
配置
{% endblock %}

{% block breadcrumb %}
    <ol class="breadcrumb" style="margin-bottom: 0;">
        <li><a href="/">首页</a></li>
        <li><a href="/asset.html">资产列表</a></li>
        <li class="active">资产详细</li>
    </ol>
{% endblock %}

{% block page-content %}

    <div style="padding: 5px 8px;">

        <div>
            <!-- Nav tabs -->
            <ul class="nav nav-tabs" role="tablist">
                <li role="presentation" class="active"><a class="no-radius" href="#basic" aria-controls="basic" role="tab"
                                                          data-toggle="tab">基本信息</a></li>
                <li role="presentation"><a class="no-radius" href="#log" aria-controls="log" role="tab"
                                           data-toggle="tab">变更记录</a></li>

            </ul>

            <!-- Tab panes -->

            <div class="tab-content">
                <div role="tabpanel" class="tab-pane active" id="basic">
                    {% include 'include/asset_basic.html' %}
                </div>

                <div role="tabpanel" class="tab-pane" id="log">
                    {% include 'include/asset_log.html' %}
                </div>

            </div>

        </div>

    </div>



{% endblock %}

{% block js %}
    <script type="text/javascript" src="/static/js/jquery.cookie.js"></script>
    <script type="text/javascript" src="/static/js/nb-list.js"></script>


    <script>
        $(function () {
            $.initMenu('#menu_asset');

        });

    </script>
{% endblock %}

templates/asset_list.html
{% extends 'index.html' %}
{% block top-css %}
    <link rel="stylesheet" href="/static/css/backend.css"/>
    <link rel="stylesheet" href="/static/css/commons.css"/>
{% endblock %}

{% block page-title %}
配置
{% endblock %}

{% block breadcrumb %}
    <ol class="breadcrumb" style="margin-bottom: 0;">
        <li><a href="/">首页</a></li>
        <li class="active">主机管理</li>
    </ol>
{% endblock %}

{% block page-content %}
<div class="row">

        <div class="panel">

    <div style="padding: 5px 8px;">

        <div class="list-block">
            <div class="clearfix search-area">

                <div class="col-md-offset-10 do-submit">
                    <a id="search_condition_submit" class="btn btn-primary no-radius">
                        <i class="fa fa-search"></i> 搜索
                    </a>
                </div>

                <div id="search_conditions" class="col-md-offset-2 col-md-8">
                    <div class="condition">
                        <div class="icons">
                            <a class="btn btn-default no-radius" onclick="$.AddSearchCondition(this)"><i
                                    class="fa fa-plus-square"></i></a>
                        </div>
                        <div class="inputs">
                            <div class="input-group">
                                <div id="search_condition" init="false" class="input-group-btn">
                                    <label type="button" class="btn btn-default no-radius" style="width: 100px;">&nbsp;</label>
                                    <button type="button" class="btn btn-default dropdown-toggle no-border-r" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><span class="caret"></span></button>
                                    <ul class="change-search-condition dropdown-menu">

                                    </ul>
                                </div>
                            </div>

                        </div>
                    </div>
                </div>

            </div>

            <div class="clearfix function-area">
                <div class="btn-group btn-group-sm custom-btn-group">
                    <a id="check_all" class="btn btn-default no-radius"><i
                            class="fa fa-check-square"></i> 全选</a>
                    <a id="check_cancel" class="btn btn-default no-radius"><i class="fa fa-minus-square-o"></i> 取消</a>
                    <a id="check_reverse" class="btn btn-default no-radius"><i
                            class="fa fa-check-square-o"></i> 反选</a>
                    <a class="btn btn-default no-radius" href="/add-asset.html"><i class="fa fa-plus-circle"></i>添加</a>
                    <a id="do_delete" class="btn btn-default no-radius"><i class="fa fa-trash"></i> 删除</a>
                    <a id="edit_mode_target" class="btn btn-default no-radius"><i class="fa fa-pencil-square-o"></i>
                        <span>进入编辑模式</span></a>
                    <a id="do_save" class="btn btn-default no-radius"><i class="fa fa-floppy-o"></i> 保存</a>
                    <a id="do_refresh" class="btn btn-default no-radius"><i class="fa fa-refresh"></i> 刷新</a>
                    <a id="handle_status" class="btn no-radius" tabindex="0" role="button" data-toggle="manual"
                       data-trigger="focus" data-container="body" data-html="true" data-placement="bottom" title="错误详细"
                       data-content=""></a>
                </div>
            </div>

            <div class="table-responsive table-area">
                <table class="table table-striped table-bordered">
                    <!-- 表格标题开始 -->
                    <thead id="table_head">
                    <tr>

                    </tr>
                    </thead>
                    <!-- 表格标题结束 -->

                    <!-- 表格内容开始 -->
                    <tbody id="table_body" edit-mode='false'>

                    </tbody>
                    <!-- 表格内容结束 -->

                </table>
                <div class="clearfix">
                    <div class="right">
                        <ul id="pager" class="pagination pagination-sm no-margin">

                        </ul>
                    </div>
                </div>
            </div>
        </div>

    </div>

    <!-- 删除层开始 -->
    <div id="modal_delete" class="alert alert-danger alert-dismissible fade in modal-delete hide" role="alert">
        <button type="button" class="close" aria-label="Close" onclick="$.Hide('#shade,#modal_delete');"><span>×</span>
        </button>
        <h4>确定删除资产？</h4>

        <p>与该资产相关联的网卡、硬盘、内存和日志等将全部被删除！<br/> &nbsp;</p>

        <p style="text-align: right">
            <button type="button" class="btn btn-danger" id="do_delete_confirm">确定删除</button>
            <button type="button" class="btn btn-default" onclick="$.Hide('#shade,#modal_delete');">取消</button>
        </p>
    </div>
    <!-- 删除层结束 -->

    <!-- 遮罩层开始 -->
    <div id='shade' class='shade hide'></div>
    <!-- 遮罩层结束 -->

    <!-- 加载层开始 -->
    <div id='loading' class='loading hide'></div>
    <!-- 加载层结束 -->
        </div>

</div>
{% endblock %}

{% block bottom-js %}
    <script type="text/javascript" src="/static/js/jquery.cookie.js"></script>
    <script type="text/javascript" src="/static/js/nb-list.js"></script>

    <script>
        $(function () {

            $.nbDataList('/assets.html');
        });


    </script>
{% endblock %}

templates/user_audit.html
{% extends 'index.html' %}
{% load custom_tag %}

{% block page-title %}
用户审计
{% endblock %}
{% block page-content %}
<div class="row" >
    <div class="col-sm-6 col-lg-3">
        <div class="panel">
            <div class="panel-heading">
                <h3 class="panel-title">用户列表</h3>
            </div>
            <div class="panel-body" >
                <div class="list-group bord-no">

                {% for department in department_list %}
                    <a data-label="department-name" class=" list-group-item" href="#"><b>{{ department }}</b><span style="color:red" class="badge badge-info">{{ department.userprofile_set.select_related|length }}</span></a>
                    {% for user in department.userprofile_set.select_related %}
                        <a data-label="username"  user-id="{{ user.id }}" style="margin-left:2%;width:96%" class="list-group-item collapse" href="/user_audit/{{ user.id }}/">&nbsp;&nbsp;&nbsp;{{ user.name }}</a>
                    {% endfor %}
                {% endfor %}
                </div>
            </div>
        </div>

    </div> <!--end col-lg-3-->
    <div class="col-sm-6 col-lg-9">
        <div class="panel">

            <div class="panel-body" style="margin-left:0" >
                {% for user in all_user %}

                    {% if user.id == user_obj.id %}
                    <div class="row" >
                        <label class="col-md-2 control-label">账户</label>
                        <div  class="col-md-9 ">
                            <b>{{ user_obj.name}}</b>

                        </div>
                    </div>
                    <div class="row" >
                        <label class="col-md-2 control-label">部门</label>
                        <div  class="col-md-9 ">
                            <b>{{ user_obj.department.name}}</b>

                        </div>
                    </div>
                    <div class="row" >
                        <label class="col-md-2 control-label">账户有效期</label>
                        <div  class="col-md-9 ">
                            从 <b>{{ user_obj.valid_begin_time }}</b> 至 <b>{{ user_obj.valid_end_time }}</b>
                            <hr/>
                        </div>
                    </div>
                    <div class="row" >
                        <label class="col-md-2 control-label">可管理主机组</label>
                        <div  class="col-md-9 ">
                            {% for group in user_obj.host_groups.select_related %}
                            {{ group.name }}<br>
                            {% endfor %}
                        <hr/>
                        </div>
                    </div>

                    <div class="row" >
                        <label class="col-md-2 control-label">可操作主机列表</label>
                        <div  class="col-md-9 ">

                            <table class="table  table-hover table-condensed">
                            <thead>
                                <tr>
                                    <th>#</th>
                                    <th>主机名</th>
                                    <th>IP</th>
                                    <th>远程用户</th>
                                </tr>
                            </thead>
                            <tbody>
                             {% for bind_host in user_obj.host_to_remote_users.select_related %}
                                <tr>
                                    <td>{{ forloop.counter }}</td>
                                    <td><a href="#fakelink" class="btn-link">{{ bind_host.host.name}}</a></td>
                                    <td>{{  bind_host.host.name }} </td>
                                    <td>{{  bind_host.remote_user.username }} </td>
                                </tr>

                            {% endfor %}

                            </tbody>
                            </table>


                         <hr/>
                        </div>
                    </div>

                    {% endif %}

                {% endfor %}
            </div>
        </div>

    </div>
</div>

<div class="row">
    <div class="col-sm-6 col-lg-12">

        <div class="panel panel-primary">

            <!--Panel heading-->
            <div class="panel-heading">
                <div class="panel-control">

                    <!--Nav tabs-->
                    <ul class="nav nav-tabs">
                        {% if data_type == 'multi_task' %}

                            <li class=""><a data-toggle="tab" href="#demo-tabs-box-1" aria-expanded="true">单机操作</a>
                            </li>
                            <li class="active"><a data-toggle="tab" href="#demo-tabs-box-2" aria-expanded="false">批量操作</a>
                            </li>
                        {% else %}
                            <li class="active"><a data-toggle="tab" href="#demo-tabs-box-1" aria-expanded="true">单机操作</a>
                            </li>
                            <li class=""><a data-toggle="tab" href="#demo-tabs-box-2" aria-expanded="false">批量操作</a>
                            </li>
                        {% endif %}
                    </ul>

                </div>

                <h3 class="panel-title"><b>{{ user_obj.name }}</b> 的操作纪录</h3>
            </div>

            <!--Panel body-->
            <div class="panel-body">

                <!--Tabs content-->
                <div class="tab-content">
                    {% if data_type == 'multi_task' %}
                    <div id="demo-tabs-box-1" class="tab-pane fade">
                    {% else %}
                    <div id="demo-tabs-box-1" class="tab-pane fade active in ">
                    {% endif %}
                      <table class="table  table-hover table-condensed">
                            <thead>
                                <tr>
                                    <th>#</th>

                                    <th>主机名</th>
                                    <th>IP</th>
                                    <th>远程用户</th>
                                    <th>登录日期</th>
                                    <th>登出日期</th>
                                    <th>操作指令数</th>
                                    <th>#</th>

                                </tr>
                            </thead>
                            <tbody>
                                {% for record in user_login_records %}
                                <tr>
                                    <td>{{ forloop.counter }}</td>
                                    <td data-label="hostname"><a href="#fakelink" class="btn-link">{{ record.host_to_remote_user.host.name}}</a></td>
                                    <td data-label="ip_addr">{{ record.host_to_remote_user.host.ip_addr }} </td>
                                    <td data-label="username">{{ record.host_to_remote_user.remote_user.username }} </td>
                                    <td data-label="login_date"><b >{{ record.date|date:"Y-m-d H:i" }}</b> </td>
                                    <td data-label="logout_date">{{ record.session.auditlog_set.select_related.last.date|date:"Y-m-d H:i" }} </td>
                                    <td>{{ record.session.auditlog_set.select_related.count}} </td>
                                    <td><a onclick="ShowRecordDetail(this,'{{ record.session.id }}')"  class="badge badge-success">查看详细</a> </td>
                                </tr>
                                {% endfor %}
                           </tbody>

                      </table>
                {% for user in all_user %}

                    {% if user.id == user_obj.id %}
                    <div class="pagination pull-right ">
                        {% pagenator2 user_login_records 'cmd_log' user_obj.id %}
                    </div>

                    </div>
                    {% if data_type == 'multi_task' %}
                    <div id="demo-tabs-box-2" class="tab-pane fade active in">
                    {% else %}
                    <div id="demo-tabs-box-2" class="tab-pane fade">
                    {% endif %}

                          <table class="table  table-hover table-condensed">
                                <thead>
                                    <tr>
                                        <th>#</th>

                                        <th>任务ID</th>
                                        <th>任务类型</th>
                                        <th>任务内容</th>
                                        <th>成功数</th>
                                        <th>失败数</th>
                                        <th>未知数</th>
                                        <th>详细</th>


                                    </tr>
                                </thead>
                                <tbody>
                                    {% for record in multitask_records %}
                                    <tr>
                                        <td>{{ forloop.counter }}</td>
                                        <td>{{ record.id }}</td>
                                        <td>{{ record.task_type }}</td>
                                        <td>{{ record.content }}</td>
                                         <td>{% query_set record.tasklogdetail_set "result" "success" %}</td>
                                        <td>{% query_set record.tasklogdetail_set "result" "failed" %}</td>
                                        <td>{% query_set record.tasklogdetail_set "result" "unknown" %}</td>
                                        <td><a class="badge badge-info" href="{% url 'multi_task_log_detail' record.id %}">查看详细</a></td>

                                    </tr>
                                    {% endfor %}
                               </tbody>

                          </table>

                        <div class="pagination pull-right ">
                                {% pagenator2 multitask_records 'multi_task' user_obj.id %}
                        </div>
                    {% endif %}

                {% endfor %}

                    </div>
                </div>
            </div>
        </div>



    </div> <!--end col-sm-6 col-lg-12-->
</div>

{% include 'user_audit_modal.html' %}


{% endblock %}
{% block aside-bar %}

{% endblock %}
{% block bottom-js %}
{% include 'user_audit_js.html' %}
<script type="text/javascript" >


    $(document).ready(function(){

        if ("{{ data_type }}" == 'multi_task'){

        }

        $("a[data-label='department-name']").click(function(){
            $(this).toggleClass('active');

            $(this).nextUntil("a[data-label='department-name']").toggleClass("collapse");
        });//end click

        $("a[data-label='username']").click(function(){

            $(this).parent().children("a[data-label='username']").removeClass("btn-default");
            $(this).addClass("btn-default");

        });//end click


        //highlight the active user when page loaded
        var active_user_ele = $("a[user-id='{{ user_obj.id }}']");
        active_user_ele.addClass('subactive')  //当前用户添加选择样式
        active_user_ele.parent().children().removeClass("collapse");    //展开当前用户id的所在组
        active_user_ele.insertAfter("a[data-label='department-name']");  // 当前用户放在最前面

        if (active_user_ele.prev().attr('data-label') == 'department-name'){
            active_user_ele.prev().toggleClass('active');
        }else{
            var parent_node = active_user_ele.prevUntil("a[data-label='department-name']")[0];
            $(parent_node).prev().toggleClass('active');

        }
        //end highlight the active user when page loaded

    });


</script>
{% endblock %}